 #+TITLE: George's Emacs Configurations
 #+AUTHOR: George Hadow
 #+STARTUP: overview
* Setup
#+begin_src emacs-lisp
  (add-to-list 'default-frame-alist '(fullscreen . maximized))
  (setq desktop-path '("~/")) 
  (desktop-save-mode 1)
  (global-set-key (kbd "C-s") (lambda () (interactive) (swiper)))
  (find-file "~/.emacs.d/my-org-config.org")
  (fset 'yes-or-no-p 'y-or-n-p)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  (smooth-scrolling-mode t)
  (setq inhibit-startup-screen t)
  (menu-bar-mode -1)
  
(setq custom-file null-device)
#+end_src
** Garbage collection
#+begin_src emacs-lisp
  (use-package gcmh
    :config

    (gcmh-mode 1))
  ;; Setting garbage collection threshold
  (setq gc-cons-threshold 402653184
	gc-cons-percentage 0.6)

    (add-hook 'emacs-startup-hook
	  (lambda ()
	    (message "*** Emacs loaded in %s with %d garbage collections."
		     (format "%.2f seconds"
			     (float-time
			      (time-subtract after-init-time before-init-time)))
		     gcs-done)))
#+end_src
* Package loading
#+begin_src emacs-lisp
  (require 'package)
  (setq package-enable-at-startup nil)
  (add-to-list 'package-archives
	       '(("melpa" . "https://melpa.org/packages/")
		 ("org" . "https://orgmode.org/elpa/")
		 ("elpa" . "https://elpa.gnu.org/packages/")))
  (package-initialize)
  ;; Bootstrap `use-package'
  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))
#+end_src
* Theme and fonts
#+begin_src emacs-lisp
  (load-theme 'modus-vivendi t)
  (marginalia-mode t)
  (setq ivy-initial-inputs-alist nil)
  (global-prettify-symbols-mode 1)

  (define-key global-map (kbd "<f5>") #'modus-themes-toggle)
  (set-face-foreground 'mode-line "gray")
  (set-face-background 'mode-line "black")
  (set-face-foreground 'line-number "#565759")
  (set-face-background 'line-number "#000000")

;; (defun fontify-frame (frame)
;; (set-frame-parameter frame 'font "Consolas-19"))
#+end_src
* Xah Lee
  #+begin_src emacs-lisp
  (add-to-list 'load-path "~/.emacs.d/lisp/")
  (require 'xah-fly-keys)
  (xah-fly-keys-set-layout "colemak-dhm")
  (xah-fly-keys 1)
  (autoload 'xah-elisp-mode "xah-elisp-mode" "xah emacs lisp major mode." t)

  ;; (define-key xah-fly-command-map (kbd ",") 'xah-backward-left-bracket)
  (define-key xah-fly-command-map (kbd "C-e") 'eval-last-sexp)
  (define-key key-translation-map (kbd "ESC") (kbd "C-g"))
  #+end_src
* Packages
#+begin_src emacs-lisp
  (use-package orderless
    :ensure t
    :custom
    (completion-styles '(orderless basic))
    (completion-category-overrides '((file (styles basic partial-completion)))))

  (use-package saveplace
    :init (save-place-mode))

    (use-package which-key
    :ensure t
    :config
    (which-key-mode))

    (use-package avy
      :ensure t
      :bind ("M-s" . avy-goto-word-0)) 
#+end_src 
* Dired
#+begin_src emacs-lisp
  (define-key dired-mode-map (kbd "DEL") 'dired-up-directory)
  (setq dired-dwim-target t)
  (setq dired-hide-details-mode 1)

  (setq dired-recursive-copies 'top)

  (setq dired-recursive-deletes 'top)
  (defun xah-dired-mode-setup ()
    "to be run as hook for `dired-mode'."
    (dired-hide-details-mode 1))

  (add-hook 'dired-mode-hook 'xah-dired-mode-setup)

  (require 'dired )
  (define-key dired-mode-map (kbd "DEL") 'dired-up-directory)
  (define-key dired-mode-map (kbd "RET") 'dired-find-alternate-file)
  (define-key dired-mode-map (kbd "^") (lambda () (interactive) (find-alternate-file "..")))
#+end_src
* Sort out
#+begin_src emacs-lisp

    (setq org-catch-invisible-edits 'smart)

	  (dolist (mode '(eshell-mode-hook
			  fundamental-mode-hook))
	    (add-hook mode (lambda () (olivetti-mode))))

	  (vertico-mode 1)
	  (global-set-key (kbd "<f1>") 'check-parens)
	  (setq save-abbrevs 'silently)
	  (put 'narrow-to-region 'disabled nil)
	  (set-face-attribute 'default nil :height 170)

	  (add-hook 'find-file-hook
		    (lambda ()
		      (when (string= (file-name-extension buffer-file-name) "el")
			(xah-elisp-mode +1))))

	  (add-hook 'find-file-hook
		    (lambda ()
		      (when (string= (file-name-extension buffer-file-name) "el")
			(xah-elisp-mode +1))))
	  (global-set-key (kbd "C-<down>") 'scroll-other-window) 
	  (global-set-key (kbd "C-<up>") 'scroll-other-window-down)
	  (define-key minibuffer-local-map (kbd "M-o") 'ivy-dispatching-done)
#+end_src
** to Delete?
:CustomCode:
	  ;; (custom-set-variables
	   ;; custom-set-variables was added by Custom.
	   ;; If you edit it by hand, you could mess it up, so be careful.
	   ;; Your init file should contain only one such instance.
	   ;; If there is more than one, they won't work right.
	   ;; '(custom-safe-themes
	     ;; '("183dfa34e360f5bc2ee4a6b3f4236e6664f4cfce40de1d43c984e0e8fc5b51ae"
      ;; default))

      ;; '(package-selected-packages
	     ;; '(avy modus-themes xclip which-key vertico-posframe use-package
      ;; try smooth-scrolling rainbow-delimiters orderless olivetti marginalia
      ;; magit key-chord helpful gcmh consult)))
	  ;; (custom-set-faces
	   ;; custom-set-faces was added by Custom.
	   ;; If you edit it by hand, you could mess it up, so be careful.
	   ;; Your init file should contain only one such instance.
	   ;; If there is more than one, they won't work right.
	   ;; )  
:END:
* Org-mode
#+begin_src emacs-lisp
  (define-key org-mode-map (kbd "C-c C-l") 'org-insert-link)
  (setq org-directory "~/OrgFiles")

  (use-package org-bullets
    :hook (( org-mode ) . org-bullets-mode))

    (setq org-confirm-babel-evaluate nil)
    (require 'org-tempo)
    (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
    (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))

  (require 'org-tempo)
    (setq org-structure-template-alist
      '(("a" . "export ascii\n")
	("el" . "emacs_lisp\n")
	;; ("C" . "comment\n")
	;; ("e" . "example\n")
	;; ("E" . "export")
	;; ("h" . "export html\n")
	;; ("l" . "export latex\n")
	;; ("q" . "quote\n")
	;; ("s" . "src")
	("v" . "verse\n")))
#+end_src
** Org-agenda
#+begin_src emacs-lisp
  (global-set-key (kbd "C-c a") 'org-agenda)
  (setq org-agenda-files
	'("~/Projects/Code/OrgFiles/Tasks.org"
	  "~/notes.org"
	  "~/Projects/Code/OrgFiles/Birthdays.org"))
  (setq-default org-catch-invisible-edits 'error) 
#+end_src
** Org-other
#+begin_src emacs-lisp
(setq org-list-demote-modify-bullet '(("+" . "-") ("-" . "+")("*" . "-")))
#+end_src
** Org-capture
#+begin_src emacs-lisp
  (global-set-key (kbd "C-c c") 'org-capture)

  (setq org-capture-templates
	'(("q" "Emacs question" entry
	   (file+headline "notes.org" "our f heading")
	   "* DEMO text %?")
	  ("p" "Promt for imput" entry
	   (file+headline "demo.org" "our f input")
	   "* %^{Please write here} %?")
	  ("o" "options for prompt" entry
	   (file+headline "demo.org" "our f heading")
	   "* %^{Select option|ONE|TWO|THREE} %?")))

  ;; M-S-LEFT (org-table-delete-column)
#+end_src

